mrs_uav_managers:
  estimation_manager:
    state_estimators: ["gps_baro"]
    initial_state_estimator: "gps_baro"
    agl_height_estimator: ""
  uav_manager:
    takeoff:
      during_takeoff: {controller: "MpcController", tracker: "LandoffTracker"}
      after_takeoff: {controller: "MpcController", tracker: "MpcTracker"}

mrs_uav_trackers:
  mpc_tracker:
    collision_avoidance:
      radius: 2.0
